root = "."
tmp_dir = "tmp"

[build]
cmd = "CGO_ENABLED=1 go build -o ./tmp/server ./cmd/api/"
bin = "./tmp/server"
include_ext = ["go", "sql"]
exclude_dir = ["tmp", "data"]

[misc]
clean_on_exit = true
